### ISSUE TITLE
Its say again: Cant get captcha list index out of range

### ISSUE THREAD

**Issue by tajlot** [plowside/Zefoy_TIKTOK_BOT#16]
Can u make any tutorial how to fix this ?

**Comment by plowside** [comment]
its cloudflare protection, i cant help

**Comment by x-o-r-r-o** [comment]
Ok so final update. I have bypassed cloudflare successfuly. 👍

**Comment by x-o-r-r-o** [comment]
Ok so here is how i managed to bypass cloudflare. First i installed a proxy server on my unraid server and configured it with Surfshark vpn and assigned a dedicated ip. so proxy server connects surfshark dedicated server and that ip becomes a http proxy via proxy server i am running on unraid and that proxy is being used in bot config which allow me to bypass cloudflare. Since this is a dedicated clean ip cloudflare never ask for captcha. I hope this will help someone if you are willing to go through all this process. Below are the tools i used.
Surfshark *Dedicated IP*
Unraid Server -> Proxy-Server *Installed in Unraid Docker*
Configured VPN in Unraid Server and Converted VPN ip to proxy via Proxy-Server
Configure HTTP Proxy in Bot Config File

**Comment by Darkfinst9** [comment]
Bro how can i Fix

**Comment by x-o-r-r-o** [comment]
> Bro how can i Fix

I have already mentioned the steps above. Use some google and some brain 🧠 that's all you need to fix this mate.

**Comment by Darkfinst9** [comment]
IT DOESNT WORK BRO

Am Mo., 27. Mai 2024 um 08:32 Uhr schrieb XORRO ***@***.***>:

**Comment by plowside** [comment]
`async def generate_schedule(users_per_levels: dict, users_dont_work_days: dict, users_vacations: dict, groups: dict, shifts: dict, schedule_range: dict):
	print(f'users_per_levels = {users_per_levels}\n', f'users_dont_work_days = {users_dont_work_days}\n', f'users_vacations = {users_vacations}\n', f'groups = {groups}\n', f'shifts = {shifts}\n', f'schedule_range = {schedule_range}\n')
	# Константы
	DAYS_IN_WEEK = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

	# Преобразование дат
	start_date = datetime.date(schedule_range['start']['year'], schedule_range['start']['month'], schedule_range['start']['day'])
	end_date = datetime.date(schedule_range['end']['year'], schedule_range['end']['month'], schedule_range['end']['day'])
	print(start_date, end_date)

	users_without_priority = {user: 0 for level in users_per_levels for user in users_per_levels[level] if level != 'R4'}

	# Функция для подсчета рабочих часов
	async def calculate_hours(start_time, end_time):
		start_dt = datetime.datetime.strptime(start_time, '%I %p')
		end_dt = datetime.datetime.strptime(end_time, '%I %p')
		if end_dt < start_dt:
			end_dt += datetime.timedelta(days=1)
		return (end_dt - start_dt).seconds / 3600

	# Подсчет рабочих часов для каждой смены
	shift_hours = {shift: await calculate_hours(info['from'], info['to']) for shift, info in shifts.items()}

	# Генерация всех дней в указанном диапазоне
	async def generate_dates(start, end):
		dates = []
		current = start
		while current <= end:
			dates.append(current)
			current += datetime.timedelta(days=1)
		return dates

	all_dates = await generate_dates(start_date, end_date)

	# Проверка, работает ли пользователь в определённый день
	def is_user_available(user, date):
		if user in users_dont_work_days and users_dont_work_days[user] == date:
			return False
		if user in users_vacations and users_vacations[user]['start'] <= date <= users_vacations[user]['end']:
			return False
		if user not in users_without_priority and (user_hours[user] - ((sum(users_without_priority.values()) / len(users_without_priority)) / 2)) > 0:
			return False
		return True

	# Инициализация структуры для отслеживания рабочих часов
	shifts_temp = {x: 0 for x in shifts}
	user_hours = dict(sorted({user: 0 for level in users_per_levels for user in users_per_levels[level]}.items(), key=lambda x: x[0]))
	user_shifts_hours = dict(sorted({user: dict(shifts_temp) for level in users_per_levels for user in users_per_levels[level]}.items(), key=lambda x: x[0]))
	
	average_hours = sum(users_without_priority.values()) / len(users_without_priority)
	# Функция для распределения пользователей по сменам
	async def assign_users_to_shifts():
		schedule = defaultdict(list)
		
		for current_date in all_dates:
			day_name = current_date.strftime('%A')
			
			for shift, info in shifts.items():
				if day_name in info['days']:
					required_users = info['users_from_groups']
					shift_duration = shift_hours[shift]
					
					assigned_users = []
					remaining_slots = 3
					
					for group, count in required_users.items():
						group_users = [user for level in groups[group] for user in users_per_levels[level] if user not in assigned_users and is_user_available(user, current_date)]
						group_users = sorted(group_users, key=lambda user: user_hours[user])
						
						if count == 'any':
							count = min(len(group_users), remaining_slots)
						else:
							count = min(count, len(group_users))
						
						selected_users = group_users[:count]
						assigned_users.extend(selected_users)
						remaining_slots -= count
					
					# Дополнение до 3 человек, если еще остались слоты
					if remaining_slots > 0:
						[user for level in groups for group in groups[level] for user in users_per_levels[group] if user not in assigned_users and is_user_available(user, current_date)]
						all_users = [user for level in groups for group in groups[level] for user in users_per_levels[group] if user not in assigned_users and is_user_available(user, current_date)]
						all_users = sorted(all_users, key=lambda user: user_hours[user])
						additional_users = all_users[:remaining_slots]
						assigned_users.extend(additional_users)

					# Обновление расписания и рабочих часов
					schedule[(current_date, shift)] = assigned_users
					for user in assigned_users:
						user_hours[user] += shift_duration
						user_shifts_hours[user][shift] += 1
						if user in users_without_priority: users_without_priority[user] += shift_duration

		return schedule

	# Генерация расписания
	schedule = await assign_users_to_shifts()

	return {'schedule': schedule, 'user_hours': user_hours, 'user_shifts_hours': user_shifts_hours}`

**Comment by plowside** [comment]
`py
async def generate_schedule(users_per_levels: dict, users_dont_work_days: dict, users_vacations: dict, groups: dict, shifts: dict, schedule_range: dict):
	print(f'users_per_levels = {users_per_levels}\n', f'users_dont_work_days = {users_dont_work_days}\n', f'users_vacations = {users_vacations}\n', f'groups = {groups}\n', f'shifts = {shifts}\n', f'schedule_range = {schedule_range}\n')
	# Константы
	DAYS_IN_WEEK = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

	# Преобразование дат
	start_date = datetime.date(schedule_range['start']['year'], schedule_range['start']['month'], schedule_range['start']['day'])
	end_date = datetime.date(schedule_range['end']['year'], schedule_range['end']['month'], schedule_range['end']['day'])
	print(start_date, end_date)

	users_without_priority = {user: 0 for level in users_per_levels for user in users_per_levels[level] if level != 'R4'}

	# Функция для подсчета рабочих часов
	async def calculate_hours(start_time, end_time):
		start_dt = datetime.datetime.strptime(start_time, '%I %p')
		end_dt = datetime.datetime.strptime(end_time, '%I %p')
		if end_dt < start_dt:
			end_dt += datetime.timedelta(days=1)
		return (end_dt - start_dt).seconds / 3600

	# Подсчет рабочих часов для каждой смены
	shift_hours = {shift: await calculate_hours(info['from'], info['to']) for shift, info in shifts.items()}

	# Генерация всех дней в указанном диапазоне
	async def generate_dates(start, end):
		dates = []
		current = start
		while current <= end:
			dates.append(current)
			current += datetime.timedelta(days=1)
		return dates

	all_dates = await generate_dates(start_date, end_date)

	# Проверка, работает ли пользователь в определённый день
	def is_user_available(user, date):
		if user in users_dont_work_days and users_dont_work_days[user] == date:
			return False
		if user in users_vacations and users_vacations[user]['start'] <= date <= users_vacations[user]['end']:
			return False
		if user not in users_without_priority and (user_hours[user] - ((sum(users_without_priority.values()) / len(users_without_priority)) / 2)) > 0:
			return False
		return True

	# Инициализация структуры для отслеживания рабочих часов
	shifts_temp = {x: 0 for x in shifts}
	user_hours = dict(sorted({user: 0 for level in users_per_levels for user in users_per_levels[level]}.items(), key=lambda x: x[0]))
	user_shifts_hours = dict(sorted({user: dict(shifts_temp) for level in users_per_levels for user in users_per_levels[level]}.items(), key=lambda x: x[0]))
	
	average_hours = sum(users_without_priority.values()) / len(users_without_priority)
	# Функция для распределения пользователей по сменам
	async def assign_users_to_shifts():
		schedule = defaultdict(list)
		
		for current_date in all_dates:
			day_name = current_date.strftime('%A')
			
			for shift, info in shifts.items():
				if day_name in info['days']:
					required_users = info['users_from_groups']
					shift_duration = shift_hours[shift]
					
					assigned_users = []
					remaining_slots = 3
					
					for group, count in required_users.items():
						group_users = [user for level in groups[group] for user in users_per_levels[level] if user not in assigned_users and is_user_available(user, current_date)]
						group_users = sorted(group_users, key=lambda user: user_hours[user])
						
						if count == 'any':
							count = min(len(group_users), remaining_slots)
						else:
							count = min(count, len(group_users))
						
						selected_users = group_users[:count]
						assigned_users.extend(selected_users)
						remaining_slots -= count
					
					# Дополнение до 3 человек, если еще остались слоты
					if remaining_slots > 0:
						[user for level in groups for group in groups[level] for user in users_per_levels[group] if user not in assigned_users and is_user_available(user, current_date)]
						all_users = [user for level in groups for group in groups[level] for user in users_per_levels[group] if user not in assigned_users and is_user_available(user, current_date)]
						all_users = sorted(all_users, key=lambda user: user_hours[user])
						additional_users = all_users[:remaining_slots]
						assigned_users.extend(additional_users)

					# Обновление расписания и рабочих часов
					schedule[(current_date, shift)] = assigned_users
					for user in assigned_users:
						user_hours[user] += shift_duration
						user_shifts_hours[user][shift] += 1
						if user in users_without_priority: users_without_priority[user] += shift_duration

		return schedule

	# Генерация расписания
	schedule = await assign_users_to_shifts()

	return {'schedule': schedule, 'user_hours': user_hours, 'user_shifts_hours': user_shifts_hours}`
