### ISSUE TITLE
Critical ERROR

### ISSUE THREAD

**Issue by MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM** [plowside/Zefoy_TIKTOK_BOT#7]
hi, so i tried using the script and it only worked once, it said "next time: 160 seconds" or something like that and then it just printed critical error 
![image](https://github.com/plowside/Zefoy_TIKTOK_BOT/assets/103538486/023538a8-73c9-4f27-842b-50f91a0502b8)

**Comment by plowside** [comment]
solved
