### ISSUE TITLE
Hearts/Follows/shares etc

### ISSUE THREAD

**Issue by burger27** [plowside/Zefoy_TIKTOK_BOT#9]
how i can switch this program for diffrent tasks like follows etc?

**Comment by burger27** [comment]
And, for example, if I have a lot of private proxies, can I use them to open more windows and increase views/follows on a video faster, etc.? Also, does Zefoy remember the last promoted video?

**Comment by plowside** [comment]
> how i can switch this program for diffrent tasks like follows etc?

config.py --> service [services u can get when runnig script]

**Comment by plowside** [comment]
> And, for example, if I have a lot of private proxies, can I use them to open more windows and increase views/follows on a video faster, etc.? Also, does Zefoy remember the last promoted video?

yes, you can, but the increasing is global, that is, even from different devices you will not be able to wind up the same video, proxies in this case are needed in order to wind up different videos at the same time

**Comment by plowside** [comment]
thanks ❤️
